dist: trusty

language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gradle

before_script:
  - git fetch

jobs:
  include:
    - stage: build
      script: echo "hello"
    - stage: deploy
      script: echo "world"