pipeline {
    agent any
    options {
        skipDefaultCheckout()
        parallelsAlwaysFailFast()
        timestamps()
        timeout(time: 1, unit: 'MINUTES')
        buildDiscarder(logRotator(numToKeepStr: '9999', artifactNumToKeepStr: '9999', daysToKeepStr: '9999'))
    }
    triggers {
        pollSCM('')
    }
    stages {
        stage('Checkout project') {
            steps {
                dir('build-folder') {
                    deleteDir()
                }
                dir('build-folder') {
                    git branch: 'my-pr',
                            url: 'https://gitlab.com/igor-dmitriev/quarkus-native-lambda'
                    script {
                        def commitSha = sh(returnStdout: true, script: "git log -n 1 --pretty=format:'%h'").trim()
                        def commitMessage = sh(returnStdout: true, script: "git log -1 --pretty=%B")
                        currentBuild.description = commitSha + " : " + commitMessage
                    }
                }
            }
        }
    }
}